<?php
// $Id$ 
function onlinerecord_perm()
{
  return array('administer onlinerecord','access onlinerecord');
}

function onlinerecord_menu()
{
  //@TODO @REFACTOR We need to change arg(n) calls in functions foo()
  //  to
  //function foo(n)
    $items=array();

    //Add main onlinerrecord settings pages
    $items['admin/settings/onlinerecord'] = array(
      'title' => t('OnlineRecord'),
      'page callback' =>  'onlinerecord_form',
      //'page arguments' => array('onlinerecord_form'),
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_NORMAL_ITEM,
    );

    /////////////////////////// Organizations //////////////////////////////////
    //Add orgs main page
    $items['admin/settings/onlinerecord/orgs'] = array(
      'title' => t('OnlineRecord organizations'),
      //'page callback' => 'drupal_get_form',
      //'page arguments' => array('onlinerecord_organizations_list'),
      'page callback' =>  'onlinerecord_orgs_list',
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'onlinerecord.admin.inc'
    );

    //Add orgs add-page
    $items['admin/settings/onlinerecord/orgs/add'] = array(
      'title' => t('Add organization'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('onlinerecord_orgs_form_add'),
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'onlinerecord.admin.inc',
    );

    //Add orgs edit-page
    $items['admin/settings/onlinerecord/orgs/%/edit'] = array(
      'title' => t('Edit organization'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('onlinerecord_orgs_form_edit',4),
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_LOCAL_TASK,
      // 'type' => MENU_NORMAL_ITEM,
      'file' => 'onlinerecord.admin.inc',
    );
      
    //Add orgs delete-page
    $items['admin/settings/onlinerecord/orgs/%/delete'] = array(
      'title' => t('Delete organization'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('onlinerecord_orgs_form_delete_confirm',4),
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'onlinerecord.admin.inc',
      
    );

    /////////////////////////// Departments ////////////////////////////////////
    //Add depts main page
    $items['admin/settings/onlinerecord/depts'] = array(
      'title' => t('OnlineRecord departments'),
      //'page callback' => 'drupal_get_form',
      //'page arguments' => array('onlinerecord_organizations_list'),
      'page callback' =>  'onlinerecord_depts_list',
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'onlinerecord.admin.inc'
    );

    //Add depts add-page
    $items['admin/settings/onlinerecord/depts/add'] = array(
      'title' => t('Add department'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('onlinerecord_depts_form_add'),
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'onlinerecord.admin.inc',
    );

    //Add depts edit-page
    $items['admin/settings/onlinerecord/depts/%/edit'] = array(
      'title' => t('Edit department'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('onlinerecord_depts_form_edit',4),
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_LOCAL_TASK,
      // 'type' => MENU_NORMAL_ITEM,
      'file' => 'onlinerecord.admin.inc',
    );

    //Add depts delete-page
    $items['admin/settings/onlinerecord/depts/%/delete'] = array(
      'title' => t('Delete department'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('onlinerecord_depts_form_delete_confirm',4),
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'onlinerecord.admin.inc',

    );
    //

    ////////////////////////////// Plans ///////////////////////////////////////
    //Add depts main page
    $items['admin/settings/onlinerecord/plans'] = array(
      'title' => t('OnlineRecord Plans'),
      //'page callback' => 'drupal_get_form',
      //'page arguments' => array('onlinerecord_organizations_list'),
      'page callback' =>  'onlinerecord_plans_list',
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'onlinerecord.admin.inc'
    );

    //Add depts add-page
    $items['admin/settings/onlinerecord/plans/add'] = array(
      'title' => t('Add plan'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('onlinerecord_plans_form_add'),
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'onlinerecord.admin.inc',
    );

    //Add depts edit-page
    $items['admin/settings/onlinerecord/plans/%/edit'] = array(
      'title' => t('Edit plan'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('onlinerecord_plans_form_edit',4),
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_LOCAL_TASK,
      // 'type' => MENU_NORMAL_ITEM,
      'file' => 'onlinerecord.admin.inc',
    );

    //Add depts delete-page
    $items['admin/settings/onlinerecord/plans/%/delete'] = array(
      'title' => t('Delete plan'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('onlinerecord_plans_form_delete_confirm',4),
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'onlinerecord.admin.inc',

    );

    //////////////////////////// Exceptions ////////////////////////////////////
    //Add depts main page
    $items['admin/settings/onlinerecord/plans/%/exceptions'] = array(
      'title' => t('Exceptions'),
      //'page callback' => 'drupal_get_form',
      //'page arguments' => array('onlinerecord_exceptions_per_plan_list',4),
      //'page callback' =>  'onlinerecord_plans_list',
      'page callback' =>  'onlinerecord_exceptions_per_plan_list',
      'page arguments' => array(4),
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'onlinerecord.admin.inc'
    );

    $items['admin/settings/onlinerecord/plans/%/exceptions/add'] = array(
      'title' => t('Add exception'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('onlinerecord_exceptions_per_plan_add',4),
      //'page callback' =>  'onlinerecord_exceptions_per_plan_add',
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'onlinerecord.admin.inc',
      'weight' => -10
    );

    $items['admin/settings/onlinerecord/exceptions'] = array(
      'title' => t('Exceptions'),
      //'page callback' => 'drupal_get_form',
      //'page arguments' => array('onlinerecord_exceptions_per_plan_list',4),
      //'page callback' =>  'onlinerecord_plans_list',
      'page callback' =>  'onlinerecord_exceptions_list',
      'page arguments' => array(4),
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_DEFAULT_LOCAL_TASK,
      'file' => 'onlinerecord.admin.inc'
    );

    $items['admin/settings/onlinerecord/exceptions/%/edit'] = array(
      'title' => t('Edit exception'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('onlinerecord_exceptions_edit',4),
      //'page callback' =>  'onlinerecord_exceptions_per_plan_add',
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'onlinerecord.admin.inc',
      'weight' => -5
    );

    $items['admin/settings/onlinerecord/exceptions/%/delete'] = array(
      'title' => t('Delete exception'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('onlinerecord_exceptions_form_delete_confirm',4),
      //'page callback' =>  'onlinerecord_exceptions_per_plan_delete',
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'onlinerecord.admin.inc',
      'weight' => 0
    );
    //////////////////////////////////Services//////////////////////////////////
     //Add services main page
    $items['admin/settings/onlinerecord/services'] = array(
      'title' => t('OnlineRecord services'),
      //'page callback' => 'drupal_get_form',
      //'page arguments' => array('onlinerecord_organizations_list'),
      'page callback' =>  'onlinerecord_services_list',
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'onlinerecord.admin.inc'
    );

    //Add services add-page
    $items['admin/settings/onlinerecord/services/add'] = array(
      'title' => t('Add service'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('onlinerecord_services_form_add'),
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'onlinerecord.admin.inc',
    );

    //Add services edit-page
    $items['admin/settings/onlinerecord/services/%/edit'] = array(
      'title' => t('Edit service'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('onlinerecord_services_form_edit',4),
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_LOCAL_TASK,
      // 'type' => MENU_NORMAL_ITEM,
      'file' => 'onlinerecord.admin.inc',
    );

    //Add services delete-page
    $items['admin/settings/onlinerecord/services/%/delete'] = array(
      'title' => t('Delete service'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('onlinerecord_services_form_delete_confirm',4),
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'onlinerecord.admin.inc',

    );

    ///////////////////////////////PLANS - SERVICES/////////////////////////////
     //Add services main page
    $items['admin/settings/onlinerecord/plans_services'] = array(
      'title' => t('OnlineRecord services'),
      //'page callback' => 'drupal_get_form',
      //'page arguments' => array('onlinerecord_organizations_list'),
      'page callback' =>  'onlinerecord_plans_services_list',
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'onlinerecord.admin.inc'
    );

    //Add services add-page
    $items['admin/settings/onlinerecord/plans_services/add'] = array(
      'title' => t('Add service'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('onlinerecord_plans_services_form_add'),
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'onlinerecord.admin.inc',
    );

    //Add services delete-page
    $items['admin/settings/onlinerecord/plans_services/%/%/delete'] = array(
      'title' => t('Delete service'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('onlinerecord_plans_services_form_delete_confirm',4),
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'onlinerecord.admin.inc',

    );

    //Plans
    $items['admin/settings/onlinerecord/plans/%/view'] = array(
      'title' => t('View plan'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('onlinerecord_plans_form_view',4),
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'onlinerecord.admin.inc',
    );
    $items['admin/settings/onlinerecord/plans/%/view/callback1'] = array(
      'page callback' => 'onlinerecord_plans_form_view_callback1',
      'access callback' => TRUE,
      'file' => 'onlinerecord.admin.inc',
      'type' => MENU_CALLBACK,
    );
    $items['admin/settings/onlinerecord/plans/%/view/callback2'] = array(
      'page callback' => 'onlinerecord_plans_form_view_callback2',
      'access callback' => TRUE,
      'file' => 'onlinerecord.admin.inc',
      'type' => MENU_CALLBACK,
    );

    //Cloning plans with all exceptions
    $items['admin/settings/onlinerecord/plans/%/clone'] = array(
      'title' => t('Clone plan'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('onlinerecord_plans_form_clone',4),
      'access arguments' => array('administer onlinerecord'),
      'type' => MENU_LOCAL_TASK,
      // 'type' => MENU_NORMAL_ITEM,
      'file' => 'onlinerecord.admin.inc',
    );


    /////////////////CHOOSE Service->Plans->Exceptions->records/////////////////
    $items['onlinerecord'] = array(
      'title' => t('Onlinerecord'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('onlinerecord_choose'),
      'access arguments' => array('access content'),
      'type' => MENU_NORMAL_ITEM,
      //'file' => 'onlinerecord.admin.inc',
    );
    return $items;
}

/**
 * Does the very standard things that must be done in any normal callback.
 * Used by each callback in this example module.
 */
function onlinerecord_form()
{
    $tableHeader = array('Onlinerecord');
    $tableData = array();
    $tableData[] = array(l('Orgs' , 'admin/settings/onlinerecord/orgs/',array('alias'=>true)));
    $tableData[] = array(l('Depts' , 'admin/settings/onlinerecord/depts/',array('alias'=>true)));
    $tableData[] = array(l('Plans' , 'admin/settings/onlinerecord/plans/',array('alias'=>true)));
    $tableData[] = array(l('Exceptions' , 'admin/settings/onlinerecord/exceptions/',array('alias'=>true)));
    $tableData[] = array(l('Services' , 'admin/settings/onlinerecord/services/',array('alias'=>true)));
    $tableData[] = array(l('Plans-Services' , 'admin/settings/onlinerecord/plans_services/',array('alias'=>true)));
    
    return theme('table', $tableHeader, $tableData);
}

function onlinerecord_choose($form_state)
{
  // Check third page
  //dpm($form_state['values']['clicked_button']);
  if (isset($form_state['storage']['page_three']))
  {
    $form['name'] =  array(
      '#title' => t('FIO'),
      '#type' => 'textfield',
      '#default_value' =>'',
    );
    /*
    $form['birthyear'] =  array(
      '#type' => 'textfield',
      '#title' => t('Date of birth'),
      '#default_value' =>'',
    );
     * 
     */

    $form['submit'] =  array(
      '#type' => 'submit',
      '#value' => t('Save'),
      '#name' => 'savebutton',
      '#id' =>'savebutton_step3',
    );
    // Check second page
  } else {
    if (isset($form_state['storage']['page_two'])) {
        $vals=onlinerecord_choose_callback2();
        $form=array();
        //Add header for table_theme
        $form['header'] = array(
          '#type' => 'value',
          '#value' => array(
             //array('data' => '#', 'field' => 'kvant_number'),
             //array('data' => 'Время', 'field' => 'time'),
             //array('data' => t('Make an appointment'), 'field' => 'button'),
             array('data' => t('time')),
             array('data' => t('-')),
          ),
        );

        $form['plan_id']['#tree']=TRUE;
        $form['plan_header']['#tree']=TRUE;
        $form['time_val']['#tree']=TRUE;
        $form['kvant_number']['#tree']=TRUE;
        foreach ($vals as $val)
        {
          if ($val[5]!=-1)
          {
              $form['plan_id'][$val[4]] = array('#type' => 'value','#value' =>$val[0][0]);
              $form['plan_header'][$val[4]] = array('#type' => 'value','#value' =>$val[1][0]);
              $form['time_val'][$val[4]] = array('#type' => 'value','#value' => $val[3]);

              $form['time'][$val[4]] = array('#value' =>$val[2]);
              //$form['time_value'][$val[4]] = array('#value' => $val[3]);
              //$form['kvant_number'][$val[4]] = array('#value' => $val[4]);
              $form['kvant_number'][$val[4]] = array('#type' => 'value','#value' => $val[4]);
              if (!empty($val[0])&&(1==1))
              {
                $form['button'][$val[4]] =  array(
                    '#type' => 'submit',
                    '#value' => t('Make an appointment'),
                    '#name' => 'button_'.$val[4],
                    '#id' => 'save_step2',

                );
              } else {
                $form['button'][$val[4]] =  array('#value' => "-");
              }
          }
          $i++;
        }
    } else // this is first page
    {
        $result=db_query('SELECT service_id, name, cabinet FROM {onlinerecord_services}');

        $services=array();
        $services[0]='---';
        $i=0;
        while ($service=db_fetch_array($result)) {
          $i=intval($service['service_id']);
          $services[$i]=$service['name'];
        }

        $default_choose_service_id = !empty($form_state['values']['choose_service_id']) ? $form_state['values']['choose_service_id'] : 0;
        $form['choose_service_id'] = array(
          '#title' => t('Select service'),
          '#type' => 'select',
          '#options' => $services,
          '#default_value' => $default_choose_service_id,
        );
        $dateformat='Y-m-d';
        $datef=date($dateformat, (time()+86400));

        $form['choose_date'] = array(
          '#title' => t('Choose date'),
          '#type' => 'date_select',
          '#default_value' => $datef,
          '#date_format' => $dateformat,
          '#date_timezone' => 'Asia/Novosibirsk',
          '#date_increment' => $kvant_value,
          '#date_year_range' => '0:+1',
          '#attributes' => array('class' => 'date-dropdown'),
        );

        $form['next'] = array(
          '#type' => 'submit',
          '#value' => t('Next >>'),
          '#name' => 'NextButton',
          '#id' =>'save_step1',
        );
    }
  }

  return $form;

}

function onlinerecord_choose_validate($form, &$form_state) {
     // Validate page 2 here
  if (isset($form_state['storage']['page_three'])) {
   
    $recordname= $form_state['values']['name'];
    if (!$recordname) {
        form_set_error('name', t('Please enter your FIO.'));
    }
    /*
    $birthyear= $form_state['values']['birthyear'];
    if (!$birthyear) {
        form_set_error('birthyear', t('Please enter your birthday date.'));
    }
     */
  } else {
      if (isset($form_state['storage']['page_two'])) {

      } else {
        $choose_service_id=$form_state['values']['choose_service_id'];
        if (!$choose_service_id)
            form_set_error('choose_service_id', t('Please choose service.'));

        $choose_date=$form_state['values']['choose_date'];
        $dateformat='Y-m-d';
        $datef=date($dateformat, (time()+86400));
        if (strtotime($choose_date)<strtotime($datef))
        {
            form_set_error('choose_date', t('Please select date correctly. You can choose only !datef or later',array('!datef' => $datef)));
        }
      }
  }
}

function onlinerecord_choose_submit($form, &$form_state)
{
  $num=explode('_',$form_state['clicked_button']['#name']);
  // Second submit
  //dpm ($form_state['clicked_button']);
  if ($form_state['clicked_button']['#id'] == 'save_step2')
  {
    $form_state['storage']['page_three'] = TRUE;
    $page_one_values = $form_state['storage']['page_one_values'];
    $form_state['storage']['page_two_values'] = $form_state['values'];
    $form_state['storage']['pressed_button'] = (int)($num[1]);

    $form_state['storage']['plan_id'] = $form_state['values']['plan_id'][(int)($num[1])];
    $form_state['storage']['plan_header'] = $form_state['values']['plan_header'][(int)($num[1])];
    $form_state['storage']['time_val']=$form_state['values']['time_val'][(int)($num[1])];
    $form_state['storage']['kvant_number']=$form_state['values']['kvant_number'][(int)($num[1])];


  } // First submit server
  elseif($form_state['clicked_button']['#id'] == 'save_step1') {
    $form_state['storage']['page_two'] = TRUE; 
    $form_state['storage']['page_one_values'] = $form_state['values'];
    unset($form_state['clicked_button']);
  }
  // Handle page 2 submissions.
  else
  {
    $page_one_values = $form_state['storage']['page_one_values'];
    $page_two_values = $form_state['storage']['page_two_values'];


    $choose_service_id=intval($page_one_values['choose_service_id']);
    $choose_date=$page_one_values['choose_date'];
    $result=db_query('Select redirect FROM {onlinerecord_services} where service_id=%d',$choose_service_id );
      $redirect = db_fetch_object($result);

    $plan_id=intval($form_state['storage']['plan_id']);
    $plan_header=$form_state['storage']['plan_header'];
    $time_val=intval($form_state['storage']['time_val']);
    $kvantn=intval($form_state['storage']['kvant_number']);
    $name=$form_state['values']['name'];
    /*$birthyear=$form_state['values']['birthyear'];

    $result=db_query("INSERT INTO {onlinerecord_records} 
      (recorddate,services_id,plan_id,kvant,name,birthyear)
      VALUES (%d,%d,%d,%d,'%s','%s')",
      strtotime($choose_date),$choose_service_id,$plan_id,$kvant_number,$name,$birthyear);
     */
    $result=db_query("INSERT INTO {onlinerecord_records}
      (recorddate,services_id,plan_id,kvant,name)
      VALUES (%d,%d,%d,%d,'%s')",
      strtotime($choose_date),$choose_service_id,$plan_id,$time_val,$name);
    $inserted_id=intval(db_result(db_query('SELECT LAST_INSERT_ID()')));
    //$num_id=$kvantn.'-'.$inserted_id;
    $num_id=$inserted_id;

    drupal_set_message(
      t('You\'ve been saved on time @time. @planh, your number is @num',
        array(
          '@time'=>strval((int)($time_val/3600)).":".str_pad(strval((int)(($time_val%3600)/60)),2,'0',STR_PAD_LEFT),//time in format hh:mm,
          '@planh'=>$plan_header,
          '@num'=>$num_id,
          )

          )
    );
    //$form_state['redirect'] = 'node';
    unset($form_state['storage']);
    $form_state['redirect']=$redirect->redirect;
  }
}

function onlinerecord_choose_callback2()
{
  $choosed_date='---';
  if (isset($_POST['choose_date']))
    $choosed_date=check_plain($_POST['choose_date']['year']).'-'.$_POST['choose_date']['month'].'-'.$_POST['choose_date']['day'];
  if (isset($_POST['choose_service_id']))
    $choose_service_id=intval($_POST['choose_service_id']);
  $ch_t=strtotime($choosed_date);

  $result=db_query('SELECT p.plan_id, p.name AS planname, p.kvant_value, p.worktimestart, p.worktimefinish,
    d.name AS deptname, o.name AS orgname, p.enabled_date, p.disabled_date
    FROM {onlinerecord_plans_services} ps, {onlinerecord_plans} p, {onlinerecord_organizations} o, {onlinerecord_departments} d
    WHERE ps.plan_id=p.plan_id
    AND p.dept_id=d.dept_id AND d.org_id=o.org_id
    AND ps.service_id=%d
    AND p.enabled_date<=%d AND %d<=p.disabled_date',$choose_service_id,$ch_t,$ch_t);
  if ($choosed_date!="")
    $chd=date('N',strtotime($choosed_date));

  $dateformat='Y-m-d';

  $i=0;
  $tableData =array();
  $tableHeader= array('pid', 'header_table','wts','wtf','kv','edate','ddate',
    'kvant_number', 'time', 'time_cmp','except_id', 'type','actions');
  $pids=array();

  while ($pid = db_fetch_object($result))
    {
        $arg=$pid->plan_id;
        //$header_table=$pid->planname." at ".$pid->deptname.", ".$pid->orgname;
        $header_table=t('@deptname , @orgname',
          array(
            '@deptname'  => $pid->deptname,
            '@orgname'  =>$pid->orgname)
        );
        $wts=$pid->worktimestart;
        $wtf=$pid->worktimefinish;
        $kvant_value=$pid->kvant_value;
        $edate=$pid->enabled_date;
        $ddate=$pid->disbled_date;
        {
        // Get all exceptions from choosen plan
          $result2=db_query("SELECT e.except_id, e.type, e.time_start, e.time_stop, e.daynumber, e.dateofexcept
            FROM {onlinerecord_exceptions} e
            WHERE e.plan_id in ('%s')
            ORDER BY plan_id",$arg);
          $j=0;
          $excepts=array();
          //exceptions to array
          while ($except = db_fetch_object($result2))
          {
            $excepts[$j++]=$except;
          }
          $exceptscount=$j;

          $result3=db_query("SELECT plan_id, kvant
            FROM {onlinerecord_records} 
            WHERE plan_id in ('%s')
            AND recorddate=%d
            ORDER BY plan_id",$arg,$ch_t);
          $j=0;
          $records=array();
          //exceptions to array
          
          while ($record = db_fetch_object($result3))
          {
              $records[intval($record->kvant)]=true;
          }
          $n=($wtf-$wts)/($kvant_value*60);

          for ($k=0;$k<$n;$k++)
          {
            $temp=$wts+$k*$kvant_value*60;
            $flag=true;
            //check exceptions for current time
            $excepts_ids="";
            $excepts_types="";
            for ($j=0;$j<$exceptscount;$j++)
            {
              //get excepts date
              $tstart=intval($excepts[$j]->time_start);
              $tstop=intval($excepts[$j]->time_stop);
              $dn=intval($excepts[$j]->daynumber);
              $dateofe=intval($excepts[$j]->dateofexcept);

              //type of exceptions processing
              switch (intval($excepts[$j]->type)) {
                case 1:
                  // try beetwen exception time
                  if (($tstart<=$temp)&&($temp<=$tstop))
                  {
                    $flag=false;
                    $excepts_ids=$excepts_ids." ". l($excepts[$j]->except_id,'admin/settings/onlinerecord/exceptions/'.$excepts[$j]->except_id.'/edit/');
                    $excepts_types=$excepts_types." ". $excepts[$j]->type.',';
                  }
                  break;
                case 2:
                  if (($tstart<=$temp)&&($temp<=$tstop)&&($chd==$dn))
                  {
                    $flag=false;
                    $excepts_ids=$excepts_ids." ". l($excepts[$j]->except_id,'admin/settings/onlinerecord/exceptions/'.$excepts[$j]->except_id.'/edit/');
                    $excepts_types=$excepts_types." ". $excepts[$j]->type.',';
                  }
                  break;
                case 5:
                  if (($tstart<=$temp)&&($temp<=$tstop)&&(strtotime($choosed_date)==$dateofe))
                  {
                    $flag=false;
                    $excepts_ids=$excepts_ids." ". l($excepts[$j]->except_id,'admin/settings/onlinerecord/exceptions/'.$excepts[$j]->except_id.'/edit/');
                    $excepts_types=$excepts_types." ". $excepts[$j]->type.',';
                  }
                  break;
              }
            }
            $valuetoseeTD=0;
            if ($flag)
            {
                $valuetoseeTD=((!$records[$temp]) ? 1 :0);
            } else $valuetoseeTD=-1;
            //InputData
            $tableData[] = array(
              $arg,//plan_id
              $header_table,//dept org
              $wts,//work_time_start
              $wtf,//work_time_finish
              $kvant_value,
              $edate,//enabled date
              $ddate,//disabled date

              $k,// Kvant number
              strval((int)($temp/3600)).":".str_pad(strval((int)(($temp%3600)/60)),2,'0',STR_PAD_LEFT),     //time in format hh:mm
              $temp,//time in seconds
              $excepts_ids,
              $excepts_types,
              (($flag)&&(!$records[$temp])) ? 1 :0,//time in seconds
              $valuetoseeTD,
            );
          }
        }
    }
    //dpm(array_search(0, array(-1,-1,-1)));
    usort($tableData,'onlinerecord_func_timecompare');
    $display_array=array();
    $flag=true;
    $counter=0;
    $counter2=0;
    $temp_time=-1;
    $i=0;
    //Sortirovka dannih
    $valuestosee_array=array();
    foreach ($tableData as $arr_str)
    {
        $i++;
        if ($arr_str[9]!=$temp_time) {
            $flag=false;
            
        }
        if ($flag)  {
            if ($arr_str[12]==1)    {
                $plans_ids_array[$counter]=$arr_str[0];
                $header_tables_array[$counter]=$arr_str[1];
                $counter++;
            }
            else $valuestosee_array[$counter2++]=$arr_str[13];
        } else {
            if ($temp_time!=-1)
                {
                $valtosave=0;
                if (!empty($plans_ids_array))
                    $valtosave=1;
                else {
                    if (array_search(0, $valuestosee_array)!=true) $valtosave=-1;
                    else $valtosave=0;
                }

                    $display_array[]=array(
                      $plans_ids_array,//plan_id
                      $header_tables_array,//dept org
                      strval((int)($temp_time/3600)).":".str_pad(strval((int)(($temp_time%3600)/60)),2,'0',STR_PAD_LEFT),     //time in format hh:mm
                      $temp_time,//time in seconds
                      $arr_str[7],//@TODO BUG: different quants possible
                      $valtosave,
                      );
                }
            $flag=true;
            $counter=0;

            $plans_ids_array=array();//plan_id
            $header_tables_array=array();//plan display name
            $valuestosee_array=array();//

            $temp_time=$arr_str[9];
            if ($arr_str[12]==1)    {
              $plans_ids_array[$counter]=$arr_str[0];
              $header_tables_array[$counter]=$arr_str[1];
              $counter++;
            }
            else $valuestosee_array[$counter2++]=$arr_str[13];
        }
    }
    $valtosave=0;
    if (!empty($plans_ids_array))
        $valtosave=1;
    else {
        if (array_search(0, $valuestosee_array)!=true) $valtosave=-1;
        else $valtosave=0;
    }

    $display_array[]=array(
              $plans_ids_array,//plan_id
              $header_tables_array,//dept org
              strval((int)($temp_time/3600)).":".str_pad(strval((int)(($temp_time%3600)/60)),2,'0',STR_PAD_LEFT),     //time in format hh:mm
              $temp_time,//time in seconds
              $arr_str[7]+1,//@TODO BUG: different quants possible
              $valtosave,
              );
    return $display_array;
}

function onlinerecord_func_timecompare($val1,$val2)
{
  if ($val1[9]==$val2[9]) return 0;
  else return ($val1[9]<$val2[9]) ? -1 :1;
}



/**
 * Реализация hook_theme()
 * Регистрируем функцию темизации формы mymodule_form_table
 */

function onlinerecord_theme() {
  return array(
    'onlinerecord_choose' => array(
      'arguments' => array('form' => NULL),
    ),
  );
}

function theme_onlinerecord_choose($form) {
  $rows = array();
  foreach (element_children($form['kvant_number']) as $key) {
    $rows[] = array(
      //drupal_render($form['kvant_number'][$key]), // дата создания
      drupal_render($form['time'][$key]),
      //drupal_render($form['time_value'][$key]),   // заголовок
      
      drupal_render($form['button'][$key])
    );
  }

  $output = theme('table', $form['header']['#value'], $rows); // выводим таблицу
  $output .= drupal_render($form);                            // выводим остальную часть формы

  return $output;
}
?>